task arretDurgence();
void demarre();
void afficheCapteurs();
void attendDepart();
void afficheErreurInt(int erreur);
void remontePince(int valeur);
void descendPince(int valeur);
void avancePendant(int temps, int puiss);
void reculePendant(int temps, int puiss);
void tourne(byte moteur, int puiss);
int suitLaLigne(int temps, int vitesse, bool enAvancant);
int suitLaLigneEnAvancant(int temps, int vitesse);
int suitLaLigneEnReculant(int temps, int vitesse);
void afficheErreur(string erreur);
void vaChercherPetit();
void vaChercherGrand();
void ramene();
void rentre();
void initialiseMoteurs();
void initialiseCapteurs();
void revient();
void stopMoteur();
void echange(int& val1, int& val2);
